const states = {
     'Pick a State' : ['Pick a State'],
     'Alabama' : ['Birmingham', 'Montgomery', 'Mobile'],
     'Alaska' : ['Anchorage', 'Fairbanks', 'Juneau'],
     'Arizona' : ['Phoenix', 'Tucson', 'Mesa'],
     'Arkansas' : ['Little Rock', 'Fort Smith', 'Fayetteville'],
     'California' : ['Los Angelos', 'San Diego', 'San Jose', 'San Fransisco', 'Anaheim'],
     'Colorado' : ['Denver', 'Colorado Springs', 'Boulder', 'Aurora'],
     'Connecticut' : ['Bridgeport', 'New Haven', 'Hartford'],
     'Delaware' : ['Wilmington', 'Dover', 'Newark'],
     'District of Columbia' : ['Washington DC'],
     'Florida' : ['Jacksonville', 'Miami', 'Tampa'],
     'Georgia' : ['Atlanta', 'Augusta', 'Columbus'],
     'Guam' : ['Tamuning', 'Mangilao', 'Yigo'],
     'Hawaii' : ['Honolulu', 'Hilo', 'Kailua'],
     'Idaho' : ['Boise', 'Nampa', 'Idaho Falls'],
     'Illinois' : ['Chicago', 'Aurora', 'Rockford', 'Springfield'],
     'Indiana' : ['Indianapolis', 'Fort Wayne', 'Evansville'],
     'Iowa' : ['Des Moines', 'Cedar Rapids', 'Davenport'],
     'Kansas' : ['Wichita', 'Kansas City', 'Lawerence', 'Manhattan'],
     'Kentucky' : ['Louisville', 'Lexington', 'Bowling Green'],
     'Louisiana' : ['New Orleans', 'Shreveport', 'Baton Rouge'],
     'Maine' : ['Portland', 'Lewiston', 'Bangor'],
     'Mariana Islands' : ['Saipan', 'Tinian', 'Rota'],
     'Maryland' : ['Baltimore', 'Frederick', 'Gaithersburg'],
     'Massachusetts' : ['Boston', 'Worcester', 'Springfield'],
     'Michigan' : ['Detroit', 'Grand Rapids', 'Warren', 'Ann Arbor'],
     'Minnesota' : ['Minneapolis', 'Saint Paul', 'Rochester'],
     'Mississippi' : ['Jackson', 'Gulfport', 'Biloxi'],
     'Missouri' : ['Kansas City', 'Saint Louis', 'Springfield'],
     'Montana' : ['Billings', 'Missoula', 'Great Falls'],
     'Nebraska' : ['Omaha', 'Lincoln', 'Hastings'],
     'Nevada' : ['Las Vegas', 'Reno', 'Henderson'],
     'New Hampshire' : ['Manchester', 'Nashua', 'Concord'],
     'New Jersey' : ['Newark', 'Jersey City', 'Paterson'],
     'New Mexico' : ['Albuquerque', 'Las Cruces', 'Rio Rancho'],
     'New York' : ['New York City', 'Buffalo', 'Rochester', 'Albany'],
     'North Carolina' : ['Charlotte', 'Raleigh', 'Greensboro'],
     'North Dakota' : ['Fargo', 'Bismarck', 'Grand Forks'],
     'Ohio' : ['Columbus', 'Cleveland', 'Cincinnati', 'Akron'],
     'Oklahoma' : ['Oklahoma City', 'Tulsa', 'Norman'],
     'Oregon' : ['Portland', 'Salem', 'Eugene'],
     'Pennsylvania' : ['Philadelphia', 'Pittsburgh', 'Allentown'],
     'Puerto Rico' : ['San Juan', 'Bayamón', 'Ponce'],
     'Rhode Island' : ['Providence', 'Warwick', 'Cranston'],
     'Samoa' : ['Tafuna', "Nu'uuli", 'Pago Pago'],
     'South Carolina' : ['Charleston', 'Columbia'],
     'South Dakota' : ['Sioux Falls', 'Rapid City', 'Aberdeen'],
     'Tennessee' : ['Memphis', 'Nashville', 'Knoxville'],
     'Texas' : ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Abilene', 'Amarillo'],
     'Utah' : ['Salt Lake City', 'West Valley City', 'Provo'],
     'Vermont' : ['Burlington', 'Rutland'],
     'Virgin Island' : ['Charlotte Amalie', "Anna's Retreat"],
     'Virginia' : ['Virginia Beach', 'Norfolk', 'Cheasapeake'],
     'Washington' : ['Seattle', 'Spokane', 'Tacoma'],
     'West Virginia' : ['Charleston', 'Huntington', 'Parkersburg'],
     'Wisconsin' : ['Milwaukee', 'Madison', 'Green Bay'],
     'Wyoming' : ['Cheyenne', 'Casper', 'Laramie']
}
export default states;